import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header/Header'
import Content from '../components/content/Content'
import Hero from '../components/hero/Hero'
import Footer from '../components/footer/Footer'
import { SearchProvider } from '../providers/SearchProvider'
import dayjs from 'dayjs'
// import styles from '../styles/Home.module.css'

export const getServerSideProps = async () => {
  const today = dayjs().format("YYYY-MM-DD")
  const res = await fetch(`https://821f21ea-3d75-4b17-bac5-f8a0fc587ad2.mock.pstmn.io/new_movies/?r_date=${today}`)
  const { data: newRelases } = await res.json()

  return { props: { newRelases } }
}

export default function Home({ newRelases }) {

  return (
    <div className='p-0 h-full'>
      <Head>
        <title>Web Assessment UI - Irfan Zahir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
      </Head>
      <SearchProvider initialValue={newRelases}>
        <Header />
        <Hero />
        <Content />
        <Footer />
      </SearchProvider>
    </div>
  )
}
