import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header/Header'
import Content from '../components/content/Content'
import Hero from '../components/hero/Hero'
import Footer from '../components/footer/Footer'
import { SearchProvider } from '../providers/SearchProvider'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className='p-0 h-full'>
      <Head>
        <title>Web Assessment UI - Irfan Zahir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
      </Head>
      <SearchProvider>
        <Header />
        <Hero />
        <Content />
        <Footer />
      </SearchProvider>
    </div>
  )
}
